{
  "hash": "a9cd53da45c318426baa82637220ef30",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Comparing Firearm Mortality to Firearm Ownership by State\nauthors:\n  - name: Grace Rinehart\n    affiliation: Colorado State University\n    roles: writing\n    corresponding: true\n  - name: Kendall Landwehr\n    affiliation: Colorado State University\n    roles: research\n    corresponding: false\n  - name: Andrew Zimbelman\n    affiliation: Colorado State University\n    roles: data collection & analysis\n    corresponding: false\nbibliography: references.bib\ncsl: apa.csl\neditor: \n  markdown: \n    wrap: 72\nexcecute:\n  echo: true\n---\n\n\n\n\n\n# Abstract\n\nThere is a notion that having more firearms makes a country or state\n“safer.” However, having more firearms per capita has been proven to\nworsen mortality rates. This issue is especially prevalent in the United\nStates, where 2nd amendment rights have become a topic of debate. In\nthis study, we aim to provide more evidence that states with high rates\nof firearm ownership have higher rates of firearm mortality. Using\nseveral statistical analyses, we highlight the correlations between\nfirearm ownership and firearm mortality. Our results showed that there\nis a significant, positive correlation between firearm ownership and\nfirearm mortality. The states with the highest rates of firearm\nownership equally had the highest rates of firearm mortality. This trend\nwas demonstrated to be exponential across the five states with the\nhighest firearm ownership percentages, as shown in both a linear\nregression model and a bar plot. By providing more insight into firearm\nmortality in relation to firearm ownership, this study hopes to\nencourage more rigorous laws regarding firearm safety and ownership\nrequirements.\n\n# Introduction\n\nThrough this study, we hope to address and provide increased analysis of\nthe problem of firearm mortality in the United States. Gun violence is a\nmajor safety, social, and public health problem within the United States\nand requires additional investigation. America has the highest\npercentage of gun ownership with an estimated 270 to 310 million\nprivately owned guns in the country (@stroebe2017dangerous). This is\ndrastically higher than any other country. For instance, Germany has\nabout 15.8 million privately owned firearms, Canada and France both have\n12.7 million, Brazil has 17.8 million, and South Africa has 5.4 million\n(@karp2018estimating). In a 2024 study with a demographically diverse\nsurvey of gun owners, the majority reported that they purchased a gun\nfor personal protection and safety (@ward2024reasons). With the goal of\nprotection in mind, the high volume of firearm death in the United\nStates is concerning. While these firearms are being purchased with the\nintention to protect, they may be causing more harm than good. \n\nGun violence has been a problem for decades, but there was a rapid\nincrease following the COVID-19 pandemic. Homicides alone increased by\n30% from 2019 to 2020 and there was an additional 7% increase in 2021\n(@braga2022gun). This shows the continued relevance of this topic and\nhow developing solutions to this crisis remains necessary. The current\nliterature suggests that within developed nations and other high income\ncountries, the U.S. is an outlier in its rates of gun mortality.\nInitially linked to America’s frontier history and culture of\ncitizen-owned guns, the U.S. continues to protect this 2nd amendment\nright and tradition of freedom, protection, and spirit of rebellion\n(@fortune2018guns). While a constitutional right, it may also be\nimportant to consider the needs of present-day society and how this\nright can be protected, yet regulated for a safer future. The large\nproportion of gun violence, mass shootings, and firearm mortality can\npartially be attributed to the weapon instrumentality effect. This is\nthe hypothesis that the presence of guns leads to higher levels of\nviolence, aggression, and lethal action when faced with a stressful or\nconflictual situation (@spieller2020gun). While some argue that\naggression and violence will occur regardless of the weapon used, the\ncapacity for lethality also has to be considered. It is much easier to\nunintentionally harm or kill someone with a firearm than a knife, for\ninstance. Understanding the relationship between firearm ownership and\nfirearm mortality through this study will contribute to this system of\nthinking. If the hypothesis that firearm ownership and firearm mortality\nare positively correlated, this study can serve as further evidence that\nadditional firearm restrictions should be implemented to protect\neveryday American people.\n\nWithin the U.S., gun mortality continues to be a major problem for its\npopulation, contributing to both mortality and morbidity. In 2020 alone,\nthe Centers for Disease Control reported 45,000 firearm-related deaths\nwith a rate of 6.1 deaths per 100,000 people. This is the highest\nreported rate since 1994 with 40% of deaths due to homicide and more\nthan half due to suicide (@fontanarosa2022unrelenting). Access to\nfirearms is also shifting suicide rates and the proportion of suicide\ndeaths by firearm. Within the 45,222 firearm deaths in 2020, 60% of\nthose were due to suicide. Similarly, among the 45,979 suicide deaths in\nthe same year, 51% of those were from a firearm injury\n(@fontanarosa2022unrelenting). These statistics present a clear need for\nadditional firearm regulation. Our study hopes to provide further\nevidence by illustrating a correlation between firearm ownership and\nfirearm mortality from the Centers for Disease Control and Prevention\nand the World Population Review.\n\n# Methods\n\nTwo datasets were used in the research project, which were obtained from\nthe Centers for Disease Control and the World Population Review. The\ndata sets were semi-cleaned beforehand in Excel. Both data sets were\nmanipulated to include a year (2022) and state column with matching\nvariable names (AK changed to Alaska, etc). Information not needed for\nanalysis, like the URLs column in the gun mortality data set, was\nremoved for clarity. Once in R Studio, a full join was used to combine\nthe data sets for analysis. A final cleaning took place in R, where\nrenaming tools were used to make column category names clear and\nconcise. Filtering tools were used to ensure that only the 50 states\nwere included in the dataset, such as the District of Columbia, which is\nalready in the dataset from Washington. From the full join, some data\ndidn’t carry over, which resulted in the manual importing of data points\ninto the dataframe. Finally, the data was arranged based on the highest\nto lowest gun ownership per household percentage.\n\nFirst, a Shapiro test was conducted to test for normality in the data.\nOnce the data was determined to be normally distributed, a Pearson test\nwas used to look at the correlation between household gun ownership\npercentage and mortality rate. Then, a linear regression model was used\nto compare the top five states with the highest gun ownership to their\nmortality rates. Finally, another linear regression model was used to\ncompare the top five states to the rest of the dataset to look for\ncorrelations and assumptions.\n\n# Results\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(readr)\nlibrary(flextable)\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(ggplot2)\nlibrary(tidymodels)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching packages ────────────────────────────────────── tidymodels 1.2.0 ──\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n✔ broom        1.0.7     ✔ rsample      1.2.1\n✔ dials        1.3.0     ✔ tibble       3.2.1\n✔ infer        1.0.7     ✔ tidyr        1.3.1\n✔ modeldata    1.4.0     ✔ tune         1.2.1\n✔ parsnip      1.2.1     ✔ workflows    1.1.4\n✔ purrr        1.0.2     ✔ workflowsets 1.1.0\n✔ recipes      1.1.0     ✔ yardstick    1.3.1\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──\n✖ purrr::compose()  masks flextable::compose()\n✖ purrr::discard()  masks scales::discard()\n✖ dplyr::filter()   masks stats::filter()\n✖ dplyr::lag()      masks stats::lag()\n✖ yardstick::spec() masks readr::spec()\n✖ recipes::step()   masks stats::step()\n• Learn how to get started at https://www.tidymodels.org/start/\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(ggpubr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'ggpubr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:flextable':\n\n    border, font, rotate\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ngun_mortality_2022 <- read.csv(\"data/gun_mortality_2022.csv\")\ngun_ownership_2022 <- read.csv(\"data/gun_ownership_2022.csv\")\n\ngun_data <- full_join(gun_mortality_2022, gun_ownership_2022, by = 'STATE')\ngun_data <- gun_data |>\n  rename(c(Year = YEAR.x,\n         State = STATE,\n         Death_Rate = RATE, \n         Deaths = DEATHS,\n         Household_pct_ownership = GunOwnership_PercentageOfHouseholdsThatOwnGuns_pct_2022,\n         GunOwnership = GunOwnership_NumOfGunLicenses_num_2022))|>\n        select(State,Death_Rate,Deaths,Household_pct_ownership,GunOwnership,Year)\ngun_data <- gun_data |>\n  filter (State != \"District of Columbia\")\n\n# Importing all values that didn't transfer over from the join\ngun_data[51,3] <- as.integer(797)\ngun_data[51,2] <- as.numeric(19.8)\ngun_data[52,3] <- as.integer(830)\ngun_data[52,2] <- as.numeric(14.0)\ngun_data[53,3] <- as.integer(1316)\ngun_data[53,2] <- as.numeric(14.9)\ngun_data[36,4] <- as.numeric(54.7)\ngun_data[36,5] <- as.integer(103368)\ngun_data[46,4] <- as.numeric(44.6)\ngun_data[46,5] <- as.integer(423707)\ngun_data[49,4] <- as.numeric(45.3)\ngun_data[49,5] <- as.integer(95430)\ngun_data[51,6] <- as.integer(2022)\ngun_data[52,6] <- as.integer(2022)\ngun_data[53,6] <- as.integer(2022)\n\ngun_data <- gun_data|>\n  arrange(-Household_pct_ownership)\n\ngun_data_con <- gun_data |>\n  arrange(-Household_pct_ownership) |>\n  head(n = 5)\n```\n:::\n\n\n\n\n\nData Visualization tools were used to give a general idea of the\nshortened dataset. Using the barplot function, a barplot was made with\nthe state as the x variable, and gun ownership % as the y variable.\nBarplot color was based on death rates using the fill function, where\nlower death rates were a darker blue, and higher death rates were a\nlighter blue. Using barplots allowed the visualization data distribution\nbefore the utilization of the Shapiro-Wilk test.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nplot1<- gun_data_con |>\nggbarplot(x = 'State', y = 'Household_pct_ownership',\n          fill = \"Death_Rate\") +\n  labs(x = \"State\", y = \"Gun Ownership Percent Per Household\",\n       title = \"Top Five States Ordered by Death Rate\") +\n  theme(legend.position = \"right\")\nprint(plot1)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Figure 1:** Barplot visualizing the household ownership based on\nstate, colored by death rate. This shows the relationship between\nhousehold gun ownership percentage and death rate.\n\nMultiple results were determined from the analysis of the shortened\ndataset. It was determined through Shapiro-Wilk tests that both gun\nownership percentage & death rate had a p value greater than 0.05, with\na p value of 0.2029 for gun ownerhsip percentage among households, and a\np value of 0.5634 for death rates.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nshapiro.test(gun_data_con$Household_pct_ownership)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  gun_data_con$Household_pct_ownership\nW = 0.85262, p-value = 0.2029\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nshapiro.test(gun_data_con$Death_Rate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  gun_data_con$Death_Rate\nW = 0.92511, p-value = 0.5634\n```\n\n\n:::\n:::\n\n\n\n\n\n**Figure 2:** Results of the Shapiro-Wilk normality test using the\nPearson method. The test showed a normal distribution.\n\nOur Pearson method correlation test showed that the variables\nHousehold_pct_ownership and Death_Rate had a correlation value of 0.905.\nThe Pearson correlation method was used because the sample data followed\na normal distribution. Plotting of Household_pct_ownership on the x-axis\nand Death_Rate on the y-axis using a ggplot function allowed for\nvisualization of this relationship. A linear regression using death_rate\nas our predicted variable, and household percent as our predictor\nvariable, was used to determine p value and r squared values to\ndetermine if a linear relationship existed. With our sample data being\nthe data used, the model provided a p value of 0.03455, and an R-squared\nvalue of 0.7591 \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ncorrelation_metric <- cor(gun_data_con$Death_Rate, gun_data_con$Household_pct_ownership,  method = \"pearson\")\nprint(correlation_metric)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.905166\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlinear_mod <- lm(Death_Rate ~ Household_pct_ownership, data = gun_data_con)\nsummary(linear_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Death_Rate ~ Household_pct_ownership, data = gun_data_con)\n\nResiduals:\n      1       2       3       4       5 \n 1.2544 -2.1618  1.2632 -0.4485  0.0927 \n\nCoefficients:\n                        Estimate Std. Error t value Pr(>|t|)  \n(Intercept)             -32.9301    14.3636  -2.293   0.1057  \nHousehold_pct_ownership   0.8382     0.2273   3.688   0.0346 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.638 on 3 degrees of freedom\nMultiple R-squared:  0.8193,\tAdjusted R-squared:  0.7591 \nF-statistic:  13.6 on 1 and 3 DF,  p-value: 0.03455\n```\n\n\n:::\n:::\n\n\n\n\n\n**Figure 3a:** Summary results on linear regression model using gun\nownership as a predictor for death rate. The regression shows a strong\nrelationship between household gun ownership percentage and death rate.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nplot2 <- ggplot(gun_data_con, aes(x = Household_pct_ownership, y = Death_Rate)) +\n  geom_point() +\n  geom_smooth(method = lm, color = 'red') +\n  labs(x = \"Gun Ownership Percent Per Household\",\n       y = \"Death Rate\",\n       title = \"Relationship Between Gun Ownership Percent Per Household and Death Rate \") +\n  theme_linedraw()\nprint(plot2)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Figure 3b:** Graph visualizing the relationship between household gun\nownership percentage and death rate. This shows that both variables\nlinearly increase together.\n\nA predicted graph was made to visualize the relationship between gun\nownership per household and death rate to determine the accuracy of our\nmodel. Using lm(household_pct_ownership \\~ death_rate, data =\ngun_data_con) representing the cleaned dataset with the top 5 states for\ngun ownership, this fit was applied to the full cleaned dataset and was\nthen visualized. This visualization found that datapoints that had lower\ngun ownership percentages had higher residual values than those with\nhigher gun ownership percentages.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nrec <- recipe(Household_pct_ownership ~ Death_Rate, data = gun_data_con)\nprep <- prep(rec)\nbaked_data <- bake(prep, new_data = gun_data_con)\n\nlm_pred <- lm(Household_pct_ownership ~ Death_Rate, data = baked_data)\nsummary(lm_pred)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Household_pct_ownership ~ Death_Rate, data = baked_data)\n\nResiduals:\n      1       2       3       4       5 \n-0.6515  2.6695 -0.9854 -0.1073 -0.9253 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)   \n(Intercept)  43.5910     5.3535   8.143  0.00387 **\nDeath_Rate    0.9774     0.2650   3.688  0.03455 * \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.769 on 3 degrees of freedom\nMultiple R-squared:  0.8193,\tAdjusted R-squared:  0.7591 \nF-statistic:  13.6 on 1 and 3 DF,  p-value: 0.03455\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nprediction_data <- augment(lm_pred, new_data = gun_data)\n```\n:::\n\n\n\n\n\n**Figure 4a:** Summary results on linear regression model using death\nrate as a predictor for gun ownership. The regression shows a strong\nrelationship between death rate and household gun ownership percentage.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\npred_data <- augment(linear_mod, newdata = gun_data)\n\npred_data %>%\nggplot(aes(x = Household_pct_ownership, y = .fitted)) +\n  geom_point(aes(color = .resid)) +\n  labs(x = \"Gun Ownership Percent Per Household\",\n       y = \"Death Rate\",\n       title = \"Predicted Death Rate Values\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n\n\n\n**Figure 4b:** Graph visualizing predicted death rate values using\nhousehold ownership percent with a linear regression from the top five\nstates, colored by residuals. This graph shows that residual values\nincrease as data moves away from our sample data.\n\n# Discussion\n\nAfter completing our analysis, the results show a strong correlation\nbetween gun ownership and gun mortality when focused specifically on the\nfive states with the highest levels of ownership. As displayed in Figure\n1, the top five states for gun ownership were Montana, Wyoming, Alaska,\nIdaho, and West Virginia. Based on the Pearson test, the two variables,\nfirearm ownership and firearm mortality, show a direct correlation. The\nresulting correlation value of 0.905 is very close to 1, showing a\nstrong positive correlation between the two variables (Figure 2). Given\nthe results of this test, it made sense to complete a linear regression.\nFrom the linear regression, a p-value of 0.03455 was produced (Figure\n3a). This shows statistical significance because the value is below\n0.05. Additionally, the resulting r-squared value of 0.7591 is between\nthe range of 0.7-0.99, showing significance (Figure 3a). Examining the\nrelationship between the percentage of households that own a firearm and\nfirearm mortality, there is a positive direct correlation. As the\npercentage of households that own a firearm increases, so does the\nfirearm mortality rate (Figure 3b). In essence, as displayed in Figure\n4b, our results show that there is a strong positive correlation between\nfirearm ownership and firearm mortality. Owning a firearm is a direct\ncontributing factor to deaths caused by firearms, at least at the state\nlevel. \n\nIn terms of the broader implications of this study, these results may be\nused as evidence for further reform to firearm ownership requirements in\nthe United States. More restrictions on the number of firearms one\nperson may own could help reduce the number of firearm-related deaths\nseen in these areas. Additionally, enacting common-sense gun laws that\nrequire additional screenings for gun purchasing and the types of\nfirearms available to the public may be necessary. For instance,\nexisting literature exploring the relationship between state firearm\nrestrictions and suicide rates shows that states with background checks,\nmandatory waiting periods, and prohibited possession show lower suicide\nrates than states without these same regulations\n(@kawano2023restrictive). If the states with fewer and more regulated\nfirearms have fewer deaths caused by firearms, it makes sense to place\nlimits and additional restrictions on the number of firearms one may\npossess. \n\nIn terms of areas for improvement, this study contains a few\nlimitations. One limitation would be the scope of this project. For\nsimplicity's sake, our project focused on the top five states with the\nhighest levels of gun ownership. However, given that there are 50 states\nwithin the United States, this means only 10 percent of the total states\nwere included in the analysis. In future analysis, more, if not all, of\nthe states could be included to fully understand the correlation\npresent. Alternatively, in addition to the top five states for\nownership, this study could have included the bottom 5 states for\nownership to provide a comparison at the other end of the spectrum.\nAdditionally, our study is limited in terms of supplemental data sets.\nWhile this study provides a clear correlation between gun ownership and\ngun mortality, it is lacking in additional variables and contributing\nfactors. As described in an article by the American Psychological\nAssociation, many risk factors may increase one’s likelihood of\nparticipating in gun violence, resulting in firearm mortality. These\nfactors include lack of employment, socioeconomic status, safety\nconcerns, and community distress (@wamser2021understanding). Finding\nrelevant and corresponding data sets could help extend the analysis in\nthis study and quantify the impact of these specific risk factors on\nfirearm mortality. \n\nFurthermore, this study relates to the broader field of data science by\nshowing how data science can be employed as a tool to inform social\nissues. This type of study is important as it takes raw data and\ntransforms it into something tangible for the public and government\nleaders to understand. As illustrated in a ScienceDirect article, data\nscience is crucial in helping make informed policy decisions in\ngovernment, from the municipal to the federal level. Just as data\nscience can provide insight and key visualizations into a city’s\ntransportation sector, it can also be used to inform decisions regarding\nfirearm regulations (@matheus2020data). Rather than developing policy\ndecisions purely based on ideas of what might be going on, this study\nsupports reformed gun laws through concrete evidence. This is also a\ndemonstration of how data science can be used to model and address\ncomplex, real-world problems such as gun mortality in the United States.\nStudies such as this also contribute to clearer communication of results\nwithin the scientific community. Being able to produce compelling\ncharts, graphs, and visualizations makes data easier to digest for a lay\naudience. For instance, in this study, Figures 4 and 5 display the\nlinear regression relating firearm ownership and mortality, clearly\nrepresenting this relationship. While the average American may not have\nknowledge of a Pearson test or be familiar with the verbiage of a linear\nregression, they likely have a basic understanding of graphs and can\nidentify a linear relationship. Making studies like this available to\nthe public is key in contributing to informed policy decisions and\nbridging the gap between data and real-world implications.\n\nAs for next steps, replication of the Pearson correlation test and\nlinear regression using more states would be ideal. Addressing one of\nthe study’s limitations, this would provide even greater evidence for\nthe correlation identified through this study. At this point, the\ncorrelation identified in this study could be used as evidence for\nreform to the current firearm ownership process. Encouraging\nrestrictions on how many firearms may be purchased by a single\nindividual or requiring additional screenings would be one approach. \n\nAdditional variables and risk factors may be added to this analysis for\neven greater and potentially more specific evidence. If taking this\napproach, narrowing the region of focus to the county level may also be\nadvantageous. Moreover, data on firearm type could also be studied. Data\nidentifying gun ownership by type of gun (e.g., handgun, hunting rifle,\nshotgun), semi-automatic, and automatic, may be used to provide more\nspecific insight into the firearm regulation needed. For example, if\nfindings illustrate that areas with a higher number of automatic rifles\nalso have the highest number of firearm mortality, this may be used as\nevidence for placing further restrictions on automatic rifle ownership.\nIf using firearm type as a contributing variable, it may be necessary to\nalso find more specific data on firearm mortality rates. Specifically,\nwithin the firearm mortality data, identifying what type of firearm that\nwas responsible for the mortality. With these changes, it may be\npossible to identify which firearms contribute most to firearm mortality\nand if there is a correlation between ownership of these types of\nfirearms and mortality caused by them.\n\n# Conclusion\n\nOverall, the Pearson test performed in this analysis resulted in a\nstatistically significant R-squared and p-value. Likewise, linear\nregression demonstrates a clear positive correlation between firearm\nownership and firearm mortality within the top five states for firearm\nownership. This study contributes to the growing evidence that further\nrestrictions on firearm ownership are necessary. Evidence suggests that\nwith a smaller percentage of households owning firearms, it is likely\nthat firearm mortality will decrease. Furthermore, this study serves as\na starting point for investigations into other contributing factors of\nfirearm mortality, in order to make specific and impactful firearm\nrestrictions.  \n\n# References\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}